@echo off
setlocal
title Whisper Flow installer

echo.
echo ===============================================
echo   Whisper Flow - installer
echo ===============================================
echo.

REM --- 1. Check Python ---
where python >nul 2>nul
if errorlevel 1 (
    echo [ERROR] Python is not on your PATH.
    echo.
    echo Install Python 3.10 or newer from:
    echo   https://www.python.org/downloads/
    echo.
    echo During install, CHECK the box "Add Python to PATH".
    echo Then re-run this script.
    pause
    exit /b 1
)

python --version
echo.

REM --- 2. Install dependencies ---
echo Installing Python dependencies (this can take a few minutes)...
python -m pip install --upgrade pip >nul 2>nul
python -m pip install -r "%~dp0requirements.txt"
if errorlevel 1 (
    echo [ERROR] pip install failed. See errors above.
    pause
    exit /b 1
)
echo.

REM --- 3. Detect pythonw.exe path ---
for /f "delims=" %%i in ('python -c "import sys, os; print(os.path.join(os.path.dirname(sys.executable), 'pythonw.exe'))"') do set "PYTHONW=%%i"
if not exist "%PYTHONW%" (
    echo [ERROR] Could not locate pythonw.exe next to python.exe.
    echo Looked for: %PYTHONW%
    pause
    exit /b 1
)
echo Found pythonw.exe at: %PYTHONW%
echo.

REM --- 4. Write run_silent.vbs with the detected path ---
set "INSTALL_DIR=%~dp0"
if "%INSTALL_DIR:~-1%"=="\" set "INSTALL_DIR=%INSTALL_DIR:~0,-1%"
>"%INSTALL_DIR%\run_silent.vbs" (
    echo ' Auto-generated by install.bat - launches Whisper Flow silently
    echo Set WshShell = CreateObject^("WScript.Shell"^)
    echo WshShell.CurrentDirectory = "%INSTALL_DIR%"
    echo WshShell.Run """%PYTHONW%"" whisper_flow.py", 0, False
)
echo Wrote run_silent.vbs

REM --- 5. Create Startup folder shortcut ---
powershell -NoProfile -Command ^
    "$ws = New-Object -ComObject WScript.Shell;" ^
    "$s  = $ws.CreateShortcut((Join-Path ([Environment]::GetFolderPath('Startup')) 'WhisperFlow.lnk'));" ^
    "$s.TargetPath = 'C:\Windows\System32\wscript.exe';" ^
    "$s.Arguments  = '\"%INSTALL_DIR%\run_silent.vbs\"';" ^
    "$s.WorkingDirectory = '%INSTALL_DIR%';" ^
    "$s.Description = 'Whisper Flow voice dictation';" ^
    "$s.Save();" ^
    "Write-Host ('Autostart shortcut created at: ' + $s.FullName)"
echo.

REM --- 6. Launch it now ---
echo Starting Whisper Flow...
start "" wscript.exe "%INSTALL_DIR%\run_silent.vbs"
echo.
echo ===============================================
echo   Done!
echo.
echo   Hold RIGHT ALT to dictate into any app.
echo   Look for the microphone icon in your system tray.
echo   It will auto-start every time you log in.
echo.
echo   To uninstall: run uninstall.bat
echo ===============================================
echo.
pause
